<a href="https://colab.research.google.com/github/sikoh/DS-Data-Wrangling-and-Storytelling/blob/main/Exploratory-Data-Analysis/DS_ExploratoryDataAnalysis_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Autograded Notebook (Canvas & CodeGrade)

This notebook will be automatically graded. It is designed to test your answers and award points for the correct answers. Following the instructions for each Task carefully.

### Instructions

* **Download this notebook** as you would any other ipynb file
* **Upload** to Google Colab or work locally (if you have that set-up)
* **Delete `raise NotImplementedError()`**
* Write your code in the `# YOUR CODE HERE` space
* **Execute** the Test cells that contain `assert` statements - these help you check your work (others contain hidden tests that will be checked when you submit through Canvas)
* **Save** your notebook when you are finished
* **Download** as a `ipynb` file (if working in Colab)
* **Upload** your complete notebook to Canvas (there will be additional instructions in Slack and/or Canvas)

# Unit 1 Sprint 1 Module 2

## EDA and Features

### Objectives

* Load and csv files
* Use basic Pandas function for data exploration
* Understand the purpose of feature engineering

#### Total notebook points: 13

**Task 1** - Load a dataset via its URL

* Create a Python list named `column_headers` with the following items: `'age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week','native-country', 'income'`.  Lists have the form `listname = ['element 1', 'element 2', element 3']`
* Load the file from the URL provided below using the `column_headers` list you created to name your columns: set the `pd.read_csv()` to `column_headers` using `names =`.  
* Name the DataFrame `adult`

In [3]:
# Task 1
import pandas as pd
import numpy as np

# URL for the dataset
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'

# YOUR CODE HERE
#raise NotImplementedError()
column_headers=['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week','native-country', 'income']

adult = pd.read_csv(data_url, names = column_headers)
# Print out your DataFrame
adult.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**Task 1 Test**

In [ ]:
# Task 1 - Test

# These tests are for you to check your work before submitting
assert isinstance(column_headers, list), 'Have you created a list of header names?'
assert len(column_headers) == 15, 'Did you include the correct number of items in the column_headers list?'
assert isinstance(adult, pd.DataFrame), 'Have you created a DataFrame named adult?'

# These tests will be completed when you submit your notebook for autograding

**Task 2** - Look at the first and last rows of the DataFrame

* Assign the first **ten (10)** rows of the `adult` DataFrame to `adult_head`
* Assign the last **ten (10)** rows of the `adult` DataFrame to `adult_tail`

In [4]:
# Task 2

# YOUR CODE HERE
#raise NotImplementedError()
adult_head = adult.head(10)
adult_tail = adult.tail(10)
# Optional: print out adult_head and adult_tail
print(adult_head)
print(adult_tail)

   age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13
1   50   Self-emp-not-inc   83311   Bachelors             13
2   38            Private  215646     HS-grad              9
3   53            Private  234721        11th              7
4   28            Private  338409   Bachelors             13
5   37            Private  284582     Masters             14
6   49            Private  160187         9th              5
7   52   Self-emp-not-inc  209642     HS-grad              9
8   31            Private   45781     Masters             14
9   42            Private  159449   Bachelors             13

           marital-status          occupation    relationship    race  \
0           Never-married        Adm-clerical   Not-in-family   White
1      Married-civ-spouse     Exec-managerial         Husband   White
2                Divorced   Handlers-cleaners   Not-in-family   White
3      Married-civ-spouse   Handlers-cleaners         Husband   Black
4      Married-civ-spouse      Prof-specialty            Wife   Black
5      Married-civ-spouse     Exec-managerial            Wife   White
6   Married-spouse-absent       Other-service   Not-in-family   Black
7      Married-civ-spouse     Exec-managerial         Husband   White
8           Never-married      Prof-specialty   Not-in-family   White
9      Married-civ-spouse     Exec-managerial         Husband   White

       sex  capital-gain  capital-loss  hours-per-week  native-country  income
0     Male          2174             0              40   United-States   <=50K
1     Male             0             0              13   United-States   <=50K
2     Male             0             0              40   United-States   <=50K
3     Male             0             0              40   United-States   <=50K
4   Female             0             0              40            Cuba   <=50K
5   Female             0             0              40   United-States   <=50K
6   Female             0             0              16         Jamaica   <=50K
7     Male             0             0              45   United-States    >50K
8   Female         14084             0              50   United-States    >50K
9     Male          5178             0              40   United-States    >50K
       age      workclass  fnlwgt      education  education-num  \
32551   32        Private   34066           10th              6
32552   43        Private   84661      Assoc-voc             11
32553   32        Private  116138        Masters             14
32554   53        Private  321865        Masters             14
32555   22        Private  310152   Some-college             10
32556   27        Private  257302     Assoc-acdm             12
32557   40        Private  154374        HS-grad              9
32558   58        Private  151910        HS-grad              9
32559   22        Private  201490        HS-grad              9
32560   52   Self-emp-inc  287927        HS-grad              9

            marital-status          occupation    relationship  \
32551   Married-civ-spouse   Handlers-cleaners         Husband
32552   Married-civ-spouse               Sales         Husband
32553        Never-married        Tech-support   Not-in-family
32554   Married-civ-spouse     Exec-managerial         Husband
32555        Never-married     Protective-serv   Not-in-family
32556   Married-civ-spouse        Tech-support            Wife
32557   Married-civ-spouse   Machine-op-inspct         Husband
32558              Widowed        Adm-clerical       Unmarried
32559        Never-married        Adm-clerical       Own-child
32560   Married-civ-spouse     Exec-managerial            Wife

                      race      sex  capital-gain  capital-loss  \
32551   Amer-Indian-Eskimo     Male             0             0
32552                White     Male             0             0
32553   Asian-Pac-Islander     Male             0             0
32554                White     Male             0             0
32555                White     Male             0             0
32556                White   Female             0             0
32557                White     Male             0             0
32558                White   Female             0             0
32559                White     Male             0             0
32560                White   Female         15024             0

       hours-per-week  native-country  income
32551              40   United-States   <=50K
32552              45   United-States   <=50K
32553              11          Taiwan   <=50K
32554              40   United-States    >50K
32555              40   United-States   <=50K
32556              38   United-States   <=50K
32557              40   United-States    >50K
32558              40   United-States   <=50K
32559              20   United-States   <=50K
32560              40   United-States    >50K

**Task 2 Test**

In [ ]:
# Task 2 - Test

# These tests are for you to check your work before submitting
assert isinstance(adult_head, pd.DataFrame), 'Have you created a DataFrame named adult_head?'
assert isinstance(adult_tail, pd.DataFrame), 'Have you created a DataFrame named adult_tail?'

# These tests will be completed when you submit your notebook for autograding

**Task 3** - Variable data types

For your `adult` DataFrame, determine the data types for the variables.

* Count the number of `int64` variable types and assign to `number_int64` (your value should be an integer)
* Count the number of `object` variable types and assign to `number_object` (your value should be an integer)

There are different ways to find the data types of the columns in a DataFrame. All you need to do for this task is to count the number of each data type and assign to the corresponding variable.

In [12]:
# Task 3

# YOUR CODE HERE
#raise NotImplementedError()

data_types = adult.dtypes
print(data_types)

number_int64 =(data_types == 'int64').sum()
print(number_int64)

number_object = (data_types == 'object').sum()
print(number_object)

age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
income            object
dtype: object
6
9

**Task 3 Test**

In [ ]:
# Task 3 - Test

# Hidden tests - you will see the results when you submit to Canvas

**Task 4** - DataFrame dimensions

* Find the dimensions of your DataFrame and assign result to the variable `adult_dimension`. Your variable should be a *tuple* and the row dimension should be listed first.

Hint: A tuple looks like this: (1, 2) - a tuple is a collection which is ordered and unchangeable. You can use the function `type(your_variable)` to print the variable type.

Hint 2: The `shape` method returns a tuple - convenient!

In [15]:
from pandas.io.pytables import AppendableMultiSeriesTable
# Task 4

# YOUR CODE HERE
#raise NotImplementedError()
adult_dimension = adult.shape
type(adult_dimension)
# Print out the shape
print(adult_dimension)

(32561, 15)

**Task 4 Test**

In [ ]:
# Task 4 - Test

assert isinstance(adult_dimension, tuple), 'Have you created a tuple named adult_dimension?'

# Hidden tests - you will see the results when you submit to Canvas

**Task 5** - Missing values

Are there any missing values in the dataset? Let's check!

* Check for missing values using `.isnull().sum()`
* Count the number of missing values and assign the value to the variable `adult_missing`. Your variable should be an integer.

In [18]:
# Task 5

# YOUR CODE HERE
#raise NotImplementedError()

adult.isnull().sum()

adult_missing = adult.isnull().sum().sum()

print(adult_missing)

0

**Task 5 Test**

In [ ]:
# Task 5 - Test

# Hidden tests - you will see the results when you submit to Canvas

**Task 6** - Viewing DataFrame statistics

Let's look at some of the *summary statistics* of our dataset. We can use the .describe() function in order to see the summary statistics of the numeric columns.

Look at the statistics for the `adult` DataFrame and then complete the following two tasks:

* Find the value for the mean `age` and assign it to the variable `mean_age` (your value should be a float and defined to two decimal places)
* Find the standard deviation (std) for the `hours-per-week` variable and assign it to `std_hpw` (your value should be a float and defined to two decimal places)

Are there any values shown that might be a code for missing data?  We'll learn how to change the values in a DataFrame in the next module.

In [28]:
adult.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [27]:
# Task 6

# YOUR CODE HERE
#raise NotImplementedError()

#Look at the statistics for the adult DataFrame
adult.describe()

#Find the value for the mean age and assign it to the variable mean_age (your value should be a float and defined to two decimal places)
mean_age = adult['age'].mean().round(2)
print(mean_age)

#Find the standard deviation (std) for the hours-per-week variable and assign it to std_hpw (your value should be a float and defined to two decimal places)
std_hpw = adult['hours-per-week'].std().round(2)
print(std_hpw)

38.58
12.35

**Task 6 Test**

In [ ]:
# Task 6 - Test

# Hidden tests - you will see the results when you submit to Canvas

**Task 7** - Summary statistics for non-numeric columns

We have some columns in this dataset that are non-numeric or object columns. This is usually a string object. Let's use the `describe()` function again but include the argument `exclude='number'` to exclude the numeric columns.

Using the results of `describe(exclude='number')`, complete the following two tasks:

* Find the number of unique `education` values and assign it to `unique_edu` (your value should be an integer)
* Find the number of times the most frequent observation for `income` occurs and assign it to `freq_income` (your value should be an integer) *(Note: this is not the income value itself, just how many times it occurs)*

In [37]:
# Task 7

# YOUR CODE HERE
#raise NotImplementedError()

#Find the number of unique education values and assign it to unique_edu (your value should be an integer)
#unique_edu = adult['education'].nunique()
#print(unique_edu)

#Find the number of times the most frequent observation for income occurs and assign it to freq_income (your value should be an integer)
freq_income = (adult['income'] == adult['income'].mode()[0]).sum()
print(freq_income)

freq_income_v2 = (adult['income'] == adult['income'].value_counts().idxmax()).sum()
print(freq_income_v2)

24720
24720

In [29]:
adult.describe(exclude='number')

,workclass,education,marital-status,occupation,relationship,race,sex,native-country,income
count,32561,32561,32561,32561,32561,32561,32561,32561,32561
unique,9,16,7,15,6,5,2,42,2
top,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,<=50K
freq,22696,10501,14976,4140,13193,27816,21790,29170,24720

**Task 7 Test**

In [ ]:
# Task 7 - Test

# Hidden tests - you will see the results when you submit to Canvas

**Task 8** - Finding value counts

Let's look more specifically at the `relationship` column and perform a count of the number of observations for each category. We can see how many categories we have by using the `.unique()` method on the column. Then, we can use `.value_counts()` to count the number of observations in each category.

* View the unique values in the `relationship` column with `.unique()`
* View the number of observations for each value with `.value_counts()`
* Find the counts for `Other-relative` and assign to the variable `adult_other_rel`

In [61]:
# Task 8

# YOUR CODE HERE
#raise NotImplementedError()

#View the unique values in the relationship column with .unique()
adult['relationship'].unique()
#View the number of observations for each value with .value_counts()
adult['relationship'].value_counts()

# Find the count for 'Other-relative' and assign it to the variable adult_other_rel
adult_other_rel = adult['relationship'].value_counts().get(' Other-relative')
adult_other_rel_v2 = adult['relationship'].value_counts()[' Other-relative']
print(adult_other_rel)
print(adult_other_rel_v2)

#NOTE:
#' Other-relative' has empty space in the string
#Use .str.strip() to remove  the leading space

981
981

**Task 8 Test**

In [ ]:
# Task 8 - Test

# Hidden tests - you will see the results when you submit to Canvas

**Task 9** - Create a Series

A column of a DataFrame is a pandas Series. Using the `adult` DataFrame, create a Series from the `occupation` column.

* Create a Series from the `occupation` column and name it `adult_occup`

In [62]:
# Task 9

# YOUR CODE HERE
#raise NotImplementedError()
adult_occup = adult['occupation']
type(adult_occup)

pandas.core.series.Series

**Task 9 Test**

In [ ]:
# Task 9 - Test

# These tests are for you to check your work before submitting
assert isinstance(adult_occup, pd.Series), 'Have you created the correct Series?'

# Hidden tests - you will see the results when you submit to Canvas

## Feature Creation

Next you will focus on learning how to create new features from exisiting data. There are many ways to create features in your datasets; we'll only focus on a few here. Let's get started!

**Task 10** - Load the data set

* Using the provided URL, load the Ames Housing Data into a DataFrame called `house`
* View your DataFrame

In [63]:
# Task 10

# Imports
import pandas as pd

# Dataset URL

data_url = 'https://raw.githubusercontent.com/LambdaSchool/data-science-practice-datasets/main/unit_1/Housing/Ames%20Iowa%20Housing%20Data.csv'

# YOUR CODE HERE
#raise NotImplementedError()
house = pd.read_csv(data_url)

# View your DataFrame
house.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

**Task 10 Test**

In [ ]:
# Task 10 - Test

# These tests are for you to check your work before submitting
assert isinstance(house, pd.DataFrame), 'Have you created a DataFrame named house?'

# Hidden tests - you'll see results when you submit to Canvas

**Task 11** - Create a new feature

Now that we have the data loaded, we're going to create a new feature. We can use the some of the existing features, in this case, the total number of bathrooms in one column.

* Create a new variable called `Total_Bathrooms` that contains the total number of full and half bathrooms in the house.  

*Hint: Identify all the columns with bath in the title and add their values together. There are four columns to add together.  Add one to the total for each full or half bathroom.*

In [75]:
# Task 11

# YOUR CODE HERE
#raise NotImplementedError()
#print(list(house.columns))
house_bath_col = house.filter(like='Bath')
#print(house_bath_col.columns)
house['Total_Bathrooms'] = house['BsmtFullBath'] + house['BsmtHalfBath'] + house['FullBath'] + house['HalfBath']
small_df_house = house[['Total_Bathrooms','BsmtFullBath','BsmtHalfBath','FullBath','HalfBath']].copy()
small_df_house.head()

   Total_Bathrooms  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath
0                4             1             0         2         1
1                3             0             1         2         0
2                4             1             0         2         1
3                2             1             0         1         0
4                4             1             0         2         1

**Task 11 Test**

In [ ]:
# Task 11 - Test

assert 'Total_Bathrooms' in house.columns, 'Did you add the new column?'

# Hidden tests - you'll see results when you submit to Canvas

# View all the bathroom columns
house[['Total_Bathrooms','BsmtFullBath','BsmtHalfBath','FullBath','HalfBath']].head()

**Task 12** - Create a new feature column

Next we're going to create another new column by "encoding" an existing column. Using the `LotArea` column, we'll assign values according the the area of the lot.

* Create a new column called `Large_Lot` that takes on the following values:
    * 0 when `LotArea` is **less** than 10,000
    * 1 when `LotArea` is **greater than or equal** to 10,000

In [79]:
# Task 12

# YOUR CODE HERE
#raise NotImplementedError()
house['Large_Lot'] = house['LotArea'].apply(lambda x: 1 if x >= 10000 else 0)

# View the new column
house[['LotArea', 'Large_Lot']].head()

   LotArea  Large_Lot
0     8450          0
1     9600          0
2    11250          1
3     9550          0
4    14260          1

**Task 12 Test**

In [ ]:
# Task 12 - Test

assert 'Large_Lot' in house.columns, 'Did you add the Large_Lot column?'

# Hidden tests - you'll see results when you submit to Canvas

**Task 13** - Create another feature

Let's continue with creating new features. This time, we'll focus on encoding for the sale month.

* Create a new column called `Summer_Sale` that takes on the following values:
    * 0 if the sale month was in September - May (`MoSold` = 1-5, 9-12)
    * 1 if the sale month was in June, July or August (`MoSold` = 6, 7 or 8)

In [82]:
# Task 13

# YOUR CODE HERE
#raise NotImplementedError()
house['Summer_Sale'] = house['MoSold'].apply(lambda x: 1 if x in [6,7,8] else 0)

# View the new column
house[['MoSold', 'Summer_Sale']].head(15)

    MoSold  Summer_Sale
0        2            0
1        5            0
2        9            0
3        2            0
4       12            0
5       10            0
6        8            1
7       11            0
8        4            0
9        1            0
10       2            0
11       7            1
12       9            0
13       8            1
14       5            0

**Task 13 Test**

In [ ]:
# Task 13 - Test

assert 'Summer_Sale' in house.columns, 'Did you add the Summer_Sale column?'

# Hidden tests - you'll see results when you submit to Canvas